### ISSUE TITLE
Readme and installation instructions

### ISSUE THREAD

**Issue by Porthmeus** [Waschina/MicrobiomeGS2#1]
Hej Silvio,

I wrote a small README.md for the repository with some instructions on how to install MicrobiomeGS into a conda environment. If you don't mind, could you add me as a collaborator so I can push the instructions and make a pull request? Otherwise, I will send the files directly here.

Best,
Jan (Taubenheim)

**Comment by Waschina** [comment]
Pull requests were possible already, and you are now also a collaborator on the project and can push the readme directly to the main branch.
